### ISSUE TITLE
using flask_login 

### ISSUE THREAD

**Issue by amangoyal05** [Saurabhkumr/Well-Mind-Wave#2]
Using flask_login along with sessions might help to maintain the user activities more easily. It would make the code simpler and easier to manage. Also, having a separate app.py file to initiate the entire code will make the loading faster. And try deserializing the model using Pickle library. It will prevent you from training the model every time, saving time and computational resources. Really liked the project. 😀

**Comment by Saurabhkumr** [comment]
thankyou for your feedback and suggestion
